### PR TITLE
update tsschecker submodule

### PR DESCRIPTION
**Pull request by DanTheMann15**
hey there, i recommend updating the tsschecker submodule with the one from my repository.
https://github.com/DanTheMann15/tsschecker

the reason why is because tihmstar's repository is (at the current time) out of date and doesn't correctly support the newer devices, among a couple of other bugs that might be restore-breaking (such as the wrong bbgcid for iPad7,12).

See [tihmstar/tsschecker=pull#165](https://github.com/tihmstar/tsschecker/pull/165) for more details.

you can see the commit history inside my [repository](https://github.com/DanTheMann15/tsschecker/commits/master) if you wish to see the changes.

take care!

### CODE REVIEW

**Comment by Cryptiiiic** [comment]
@DanTheMann15 seems pretty cool to me, can you test it with my latest commit, 192?

**Comment by DanTheMann15** [comment]
sure, i'll try it on linux, since it's easy as pie there.

windows on the other hand is a mighty pain in the ass, it'll be awhile before i can reliably build futurerestore statically on windows, perhaps ask opa334.

i don't have a mac so i can't do anything for that platform.

**Comment by DanTheMann15** [comment]
I'm not completely sure why i am getting errors related to this when compiling on linux,
`In file included from futurerestore.cpp:9:
/usr/local/include/libgeneral/macros.h:55:13: error: #include expects "FILENAME" or <FILENAME>
   55 | #   include CUSTOM_LOGGING
      |             ^~~~~~~~~~~~~~`

here's the full log: [buildlog.txt](https://github.com/marijuanARM/futurerestore/files/6060996/buildlog.txt)

i sometimes wonder why libgeneral can be a pain in the ass sometimes.

EDIT: Stops me dead on Windows as well.
[Winbuild.txt](https://github.com/marijuanARM/futurerestore/files/6061278/Winbuild.txt)

**Comment by Cryptiiiic** [comment]
@DanTheMann15 
linux fix, just comment out that line
`sed -i 's|#   include CUSTOM_LOGGING|//#   include CUSTOM_LOGGING|' /usr/local/include/libgeneral/macros.h`

**Comment by DanTheMann15** [comment]
Success on iPhone 7 Plus (d11)

[restorelog_iPhone9,2.txt](https://github.com/marijuanARM/futurerestore/files/6066112/restorelog_iPhone9.2.txt)

**Comment by DanTheMann15** [comment]
To reproduce:


>git clone https://github.com/marijuanARM/futurerestore.git
>cd futurerestore
>git rm external/idevicerestore
>git rm external/tsschecker
>git submodule add https://github.com/DanTheMann15/tsschecker.git external/tsschecker
>git submodule add https://github.com/marijuanARM/idevicerestore.git external/idevicerestore
>git submodule update --init
>git submodule update --init --recursive
>./autogen.sh
>make
>make install

**Comment by opa334** [comment]
> windows on the other hand is a mighty pain in the ass, it'll be awhile before i can reliably build futurerestore statically on windows, perhaps ask opa334.

check out my build script: https://github.com/opa334/futurerestore-compile-windows

**Comment by DanTheMann15** [comment]
> 
> 
> > windows on the other hand is a mighty pain in the ass, it'll be awhile before i can reliably build futurerestore statically on windows, perhaps ask opa334.
> 
> check out my build script: https://github.com/opa334/futurerestore-compile-windows

That build script worked like a charm! - thanks!
i modified it a little so that futurerestore compiles with my fork of tsschecker and it was a successful restore: [restorelog_win.txt](https://github.com/marijuanARM/futurerestore/files/6070568/restorelog_win.txt)
note that it's not the complete log since my command prompt is set to 300 lines in it's buffer, i got to increase that, but the important part of the log is there.

and here's version of your script i modified (incase you want to see it): [buildscript_modified.zip](https://github.com/marijuanARM/futurerestore/files/6070579/buildscript_modified.zip)

**Comment by DanTheMann15** [comment]
when you go to merge this PR, make sure to update the tsschecker submodule to the latest version.

i made a commit implementing opa334's fix found in the build script, it worked on windows as well as linux.

**Comment by DanTheMann15** [comment]
tsschecker submodule updated in my fork, it now has opa334's patches built in. it's tested to work properly on Windows and Linux.

when you merge this PR, it's better to squash and merge so this appears as one commit, as you're only changing the repo for tsschecker.

**Comment by Cryptiiiic** [comment]
@DanTheMann15 since I took over, I had adam add all the standard branch features such as squash and merge, etc. :)
so just make sure everything is pushed.

**Comment by DanTheMann15** [comment]
it's pushed to the latest v331.0. ;)

**Pull request merged**
