### PR TITLE
Since some users seem confused about this.

### PR DESCRIPTION
**Pull request by HydrationMan**

### CODE REVIEW

**Comment by Cryptiiiic** [comment]
No, please combine my message with yours

**Comment by HydrationMan** [comment]
Yeah post pr'ing this I did think it was a bit long

**Comment by Cryptiiiic** [comment]
It needs to say which option was a fault

**Comment by HydrationMan** [comment]
that too, making changes without thinking about it moment

**Review by Cryptiiiic — APPROVED** [review]

**Pull request merged**
